FROM artifacts.developer.gov.bc.ca/docker-remote/node:22.13.1

COPY . .

RUN pwd \
    && ls -l \
    && npm install \
    && npx prisma generate \
    && npm run build

EXPOSE 3000

CMD [ "npm" , "run" , "start" ]