 # This workflow builds and deploys the Zeva2 application to the production environment in OpenShift.

name: Zeva2 Prod CI

on:
  pull_request:
    types: [closed]
    branches:
      - main
  workflow_dispatch:
    inputs:
      branch:
        description: 'Please carefully choose the branch merged into main, it impacts the versioning'
        required: false

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  on-merge-only:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: show pr
        run: |
         echo "PR #${{ github.event.pull_request.number }} was merged from ${{ github.event.pull_request.head.ref }}"
       
  versioning:
    runs-on: ubuntu-latest
    needs: [on-merge-only]
    outputs:
      VERSION: ${{ steps.export-version.outputs.VERSION }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Create tag on the commit on Main
        run: |
          ref="${{ github.event.pull_request.head.ref }}"   # e.g. "release/0.1.0"
          version="${ref##*/}"                              # => "0.1.0"
          git config --global user.email "kuan.fan@gov.bc.ca"
          git config --global user.name "Kuan Fan"
          git tag -a "$version" -m "prod-ci tag $version"
          git push origin "$version"

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v3.1.11
        with:
          versionSpec: "6.0.x"

      - name: Determine Version
        id: version-step # step id used as reference for output values
        uses: gittools/actions/gitversion/execute@v3.1.11
        with:
          useConfigFile: true

      - name: Export Version
        id: export-version
        run: |
          echo "VERSION=${{ steps.version-step.outputs.SemVer }}"
          echo "VERSION=${{ steps.version-step.outputs.SemVer }}" >> $GITHUB_OUTPUT
  
